name: Update README

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  markscribe:
    runs-on: ubuntu-latest
    # THIS SECTION IS KEY: It gives the bot permission to edit your README
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run Markscribe
        uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_API_URL: https://hackatime.hackclub.com/api/v1
        with:
          template: "README.md.tpl"
          writeTo: "README.md"
