name: Update README

on:
  schedule:
    - cron: "0 */1 * * *" # This runs it every hour
  workflow_dispatch:      # This adds a "Run" button so you can test it manually

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: muesli/readme-scribe@master
        env:
          # This connects to the secret you saved in your settings
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # This tells it to use Hackatime instead of standard WakaTime
          WAKATIME_API_URL: https://hackatime.hackclub.com/api/v1
        with:
          template: "README.md.tpl"
          writeTo: "README.md"
